SGID/Models/Gerencial/RelatorioCirurgiaNFaturada/CirurgiasN.cs
namespace SGID.Models.Gerencial.RelatorioCirurgiaNFaturada
{
    public class CirurgiasN
    {
        public string NomeVend { get; set; }
        public string Emissao { get; set; }
        public string Numero { get; set; }
        public string CliFat { get; set; }
        public string CliEnt { get; set; }
        public string Paciente { get; set; }
        public string TipoOper { get; set; }
        public string TipoCli { get; set; }
        public string DataCirurgia { get; set; }
        public double ValTot { get; set; }
        public double Descont { get; set; }
        public double Dias { get; set; }
        public string Periodo { get; set; }
        public string Order { get; set; }
    }
}

SGID/Models/Gerencial/RelatorioCirurgiaNFaturada/Operacao.cs
namespace SGID.Models.Gerencial.RelatorioCirurgiaNFaturada
{
    public class Operacao
    {
        public string Emissao { get; set; }
        public string Numero { get; set; }
        public string Nome { get; set; }
        public string Paciente { get; set; }
        public string Medico { get; set; }
        public string TipoOper { get; set; }
        public string TipoCli { get; set; }
        public string UPatrim { get; set; }
        public string DataCirurgia { get; set; }
        public double Dias { get; set; }
        public string Periodo { get; set; }
        public string Order { get;set; }
        public double Valor { get; set; }
    }
}

SGID/Models/Gerencial/RelatorioTabela.cs
namespace SGID.Models.Gerencial
{
    public class RelatorioTabela
    {
        public string CodProd { get; set; }
        public string DescProd { get; set; }
        public string DescGrup { get; set; }
        public string Bloqueado { get; set; }
        public string Fabricante { get; set; }
        public double CodTab { get; set; }
    }
}

SGID/Models/Gerencial/RelatorioTabelasProdNCadastrados.cs
namespace SGID.Models.Gerencial
{
    public class RelatorioTabelasProdNCadastrados
    {
        public string Codigo { get; set; }
        public string Descricao { get; set; }
        public string Grupo { get; set; }
        public string Fabricante { get; set; }
        public string Bloqueado { get; set; }
    }
}

SGID/Pages/Relatorios/AdmVendas/PedidosTriagem.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using OfficeOpenXml;
using SGID.Data;
using SGID.Data.Models;
using SGID.Models;
using SGID.Models.Denuo;

namespace SGID.Pages.Relatorios.AdmVendas
{

    [Authorize]
    public class PedidosTriagemModel : PageModel
    {
        private TOTVSDENUOContext Protheus { get; set; }
        private ApplicationDbContext SGID { get; set; }
        public List<RelatorioPedidosTriagem> Relatorios { get; set; } = new List<RelatorioPedidosTriagem>();

        public PedidosTriagemModel(TOTVSDENUOContext protheus, ApplicationDbContext sgid)
        {
            Protheus = protheus;
            SGID = sgid;
        }
        public void OnGet()
        {
            try
            {
                Relatorios = Protheus.Sc5010s.Where(x => x.DELET != "*" && x.C5Nota == "" && x.C5Utpoper == "T")
                    .OrderBy(x => x.C5XDtcir).ThenBy(x => x.C5Emissao).Select(x =>
                    new RelatorioPedidosTriagem
                    {
                        Filial = x.C5Filial,
                        NumPedido = x.C5Num,
                        CodCliente = x.C5Cliente,
                        CodLoja = x.C5Lojacli,
                        NomCliente = x.C5Nomcli.Trim(),
                        DTCirurgia = $"{x.C5XDtcir.Substring(6, 2)}/{x.C5XDtcir.Substring(4, 2)}/{x.C5XDtcir.Substring(0, 4)}",
                        DTEmissao = $"{x.C5Emissao.Substring(6, 2)}/{x.C5Emissao.Substring(4, 2)}/{x.C5Emissao.Substring(0, 4)}",
                        Paciente = x.C5XNmpac.Trim(),
                    }).ToList();
            }
            catch (Exception e)
            {
                string user = User.Identity.Name.Split("@")[0].ToUpper();
                Logger.Log(e, SGID, "PedidosTriagem", user);
            }
        }

        public IActionResult OnPostExport()
        {
            try
            {
                Relatorios = Protheus.Sc5010s.Where(x => x.DELET != "*" && x.C5Nota == "" && x.C5Utpoper == "T")
                    .OrderBy(x => x.C5XDtcir).ThenBy(x => x.C5Emissao).Select(x =>
                    new RelatorioPedidosTriagem
                    {
                        Filial = x.C5Filial,
                        NumPedido = x.C5Num,
                        CodCliente = x.C5Cliente,
                        CodLoja = x.C5Lojacli,
                        NomCliente = x.C5Nomcli.Trim(),
                        DTCirurgia = $"{x.C5XDtcir.Substring(6, 2)}/{x.C5XDtcir.Substring(4, 2)}/{x.C5XDtcir.Substring(0, 4)}",
                        DTEmissao = $"{x.C5Emissao.Substring(6, 2)}/{x.C5Emissao.Substring(4, 2)}/{x.C5Emissao.Substring(0, 4)}",
                        Paciente = x.C5XNmpac.Trim(),
                    }).ToList();

                using ExcelPackage package = new ExcelPackage();
                package.Workbook.Worksheets.Add("Pedidos Triagem");

                var sheet = package.Workbook.Worksheets.SingleOrDefault(x => x.Name == "Pedidos Triagem");

                sheet.Cells[1, 1].Value = "Filial";
                sheet.Cells[1, 2].Value = "NumPedido";
                sheet.Cells[1, 3].Value = "CodCliente";
                sheet.Cells[1, 4].Value = "CodLoja";
                sheet.Cells[1, 5].Value = "NomCliente";
                sheet.Cells[1, 6].Value = "DTCirurgia";
                sheet.Cells[1, 7].Value = "DTEmissao";
                sheet.Cells[1, 8].Value = "Paciente";

                int i = 2;

                Relatorios.ForEach(Pedido =>
                {
                    sheet.Cells[i, 1].Value = Pedido.Filial;
                    sheet.Cells[i, 2].Value = Pedido.NumPedido;
                    sheet.Cells[i, 3].Value = Pedido.CodCliente;
                    sheet.Cells[i, 4].Value = Pedido.CodLoja;
                    sheet.Cells[i, 5].Value = Pedido.NomCliente;
                    sheet.Cells[i, 6].Value = Pedido.DTCirurgia;
                    sheet.Cells[i, 7].Value = Pedido.DTEmissao;
                    sheet.Cells[i, 8].Value = Pedido.Paciente;

                    i++;
                });

                //var format = sheet.Cells[i, 3, i, 4];
                //format.Style.Numberformat.Format = "";

                sheet.Cells[sheet.Dimension.Address].AutoFitColumns();
                using MemoryStream stream = new MemoryStream();
                package.SaveAs(stream);
                return File(stream.ToArray(), "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", "PedidosTriagem.xlsx");
            }
            catch (Exception e)
            {
                string user = User.Identity.Name.Split("@")[0].ToUpper();
                Logger.Log(e, SGID, "PedidosTriagem Excel", user);

                return LocalRedirect("/error");
            }
        }
    }
}

SGID/Pages/Relatorios/AdmVendas/PedidosTriagemInter.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using SGID.Models.Inter;
using OfficeOpenXml;
using SGID.Data;
using SGID.Data.Models;
using SGID.Models;

namespace SGID.Pages.Relatorios.AdmVendas
{

    [Authorize]
    public class PedidosTriagemInterModel : PageModel
    {
        private TOTVSINTERContext Protheus { get; set; }
        private ApplicationDbContext SGID { get; set; }
        public List<RelatorioPedidosTriagem> Relatorios { get; set; } = new List<RelatorioPedidosTriagem>();

        public PedidosTriagemInterModel(TOTVSINTERContext protheus,ApplicationDbContext sgid)
        {
            Protheus = protheus;
            SGID = sgid;
        }
        public void OnGet()
        {
            try
            {
                Relatorios = Protheus.Sc5010s.Where(x => x.DELET != "*" && x.C5Nota == "" && x.C5Utpoper == "T")
                    .OrderBy(x => x.C5XDtcir).ThenBy(x => x.C5Emissao).Select(x =>
                    new RelatorioPedidosTriagem
                    {
                        Filial = x.C5Filial,
                        NumPedido = x.C5Num,
                        CodCliente = x.C5Cliente,
                        CodLoja = x.C5Lojacli,
                        NomCliente = x.C5Nomcli.Trim(),
                        DTCirurgia = $"{x.C5XDtcir.Substring(6, 2)}/{x.C5XDtcir.Substring(4, 2)}/{x.C5XDtcir.Substring(0, 4)}",
                        DTEmissao = $"{x.C5Emissao.Substring(6, 2)}/{x.C5Emissao.Substring(4, 2)}/{x.C5Emissao.Substring(0, 4)}",
                        Paciente = x.C5XNmpac.Trim(),
                    }).ToList();
            }
            catch (Exception e)
            {
                string user = User.Identity.Name.Split("@")[0].ToUpper();
                Logger.Log(e, SGID, "PedidosTriagemInter",user);
            }
        }

        public IActionResult OnPostExport()
        {
            try
            {
                Relatorios = Protheus.Sc5010s.Where(x => x.DELET != "*" && x.C5Nota == "" && x.C5Utpoper == "T")
                    .OrderBy(x => x.C5XDtcir).ThenBy(x => x.C5Emissao).Select(x =>
                    new RelatorioPedidosTriagem
                    {
                        Filial = x.C5Filial,
                        NumPedido = x.C5Num,
                        CodCliente = x.C5Cliente,
                        CodLoja = x.C5Lojacli,
                        NomCliente = x.C5Nomcli.Trim(),
                        DTCirurgia = $"{x.C5XDtcir.Substring(6, 2)}/{x.C5XDtcir.Substring(4, 2)}/{x.C5XDtcir.Substring(0, 4)}",
                        DTEmissao = $"{x.C5Emissao.Substring(6, 2)}/{x.C5Emissao.Substring(4, 2)}/{x.C5Emissao.Substring(0, 4)}",
                        Paciente = x.C5XNmpac.Trim(),
                    }).ToList();

                using ExcelPackage package = new ExcelPackage();
                package.Workbook.Worksheets.Add("Pedidos Triagem");

                var sheet = package.Workbook.Worksheets.SingleOrDefault(x => x.Name == "Pedidos Triagem");

                sheet.Cells[1, 1].Value = "Filial";
                sheet.Cells[1, 2].Value = "NumPedido";
                sheet.Cells[1, 3].Value = "CodCliente";
                sheet.Cells[1, 4].Value = "CodLoja";
                sheet.Cells[1, 5].Value = "NomCliente";
                sheet.Cells[1, 6].Value = "DTCirurgia";
                sheet.Cells[1, 7].Value = "DTEmissao";
                sheet.Cells[1, 8].Value = "Paciente";

                int i = 2;

                Relatorios.ForEach(Pedido =>
                {
                    sheet.Cells[i, 1].Value = Pedido.Filial;
                    sheet.Cells[i, 2].Value = Pedido.NumPedido;
                    sheet.Cells[i, 3].Value = Pedido.CodCliente;
                    sheet.Cells[i, 4].Value = Pedido.CodLoja;
                    sheet.Cells[i, 5].Value = Pedido.NomCliente;
                    sheet.Cells[i, 6].Value = Pedido.DTCirurgia;
                    sheet.Cells[i, 7].Value = Pedido.DTEmissao;
                    sheet.Cells[i, 8].Value = Pedido.Paciente;

                    i++;
                });

                //var format = sheet.Cells[i, 3, i, 4];
                //format.Style.Numberformat.Format = "";

                sheet.Cells[sheet.Dimension.Address].AutoFitColumns();
                using MemoryStream stream = new MemoryStream();
                package.SaveAs(stream);
                return File(stream.ToArray(), "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", "PedidosTriagemInter.xlsx");
            }
            catch (Exception e)
            {
                string user = User.Identity.Name.Split("@")[0].ToUpper();
                Logger.Log(e, SGID, "PedidosTriagemInter Excel", user);

                return LocalRedirect("/error");
            }
        }
    }
}

SGID/Pages/Relatorios/Cirurgias/CadastrosMedicosInter.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using SGID.Models.Inter;
using OfficeOpenXml;
using SGID.Data;
using SGID.Data.Models;
using SGID.Models;

namespace SGID.Pages.Relatorios.Cirurgias
{
    [Authorize]
    public class CadastrosMedicosInterModel : PageModel
    {
        private TOTVSINTERContext Protheus { get; set; }
        private ApplicationDbContext SGID { get; set; }

        public List<RelatorioCadastroMedicos> Relatorio { get; set; } = new List<RelatorioCadastroMedicos>();

        public int CurrentPage { get; set; }

        public int TotalPages { get; set; }

        public CadastrosMedicosInterModel(TOTVSINTERContext context,ApplicationDbContext sgid)
        {
            Protheus = context;
            SGID = sgid;
        }
        public void OnGet(int id)
        {
            try
            {
                CurrentPage = id;

                TotalPages = (int)Math.Ceiling(decimal.Divide((from SA10 in Protheus.Sa1010s
                                                               join SA30 in Protheus.Sa3010s on SA10.A1Vend equals SA30.A3Cod
                                                               where SA10.DELET != "*" && SA10.A1Msblql != "1" && SA10.A1Clinter == "M"
                                                               && SA30.DELET != "*"
                                                               select SA10.A1Nome).Count(), 20));

                Relatorio = (from SA10 in Protheus.Sa1010s
                             join SA30 in Protheus.Sa3010s on SA10.A1Vend equals SA30.A3Cod
                             where SA10.DELET != "*" && SA10.A1Msblql != "1" && SA10.A1Clinter == "M"
                             && SA30.DELET != "*"
                             orderby SA10.A1Cod descending
                             select new RelatorioCadastroMedicos
                             {
                                 Codigo = SA10.A1Cod,
                                 Nome = SA10.A1Nome,
                                 CodVenda = SA10.A1Vend,
                                 Nome2 = SA30.A3Nome,
                                 Telefone = SA10.A1Tel,
                                 Celular = SA10.A1Celular,
                                 Municipio = SA10.A1Mun,
                                 Estado = SA10.A1Est
                             }
                            ).Skip((CurrentPage - 1) * 20).Take(20).ToList();
            }
            catch (Exception e)
            {
                string user = User.Identity.Name.Split("@")[0].ToUpper();
                Logger.Log(e, SGID, "CadastroMedicosInter",user);

            }
        }
        public IActionResult OnPostExport()
        {
            try
            {
                Relatorio = (from SA10 in Protheus.Sa1010s
                             join SA30 in Protheus.Sa3010s on SA10.A1Vend equals SA30.A3Cod
                             where SA10.DELET != "*" && SA10.A1Msblql != "1" && SA10.A1Clinter == "M"
                             && SA30.DELET != "*"
                             orderby SA10.A1Cod descending
                             select new RelatorioCadastroMedicos
                             {
                                 Codigo = SA10.A1Cod,
                                 Nome = SA10.A1Nome,
                                 CodVenda = SA10.A1Vend,
                                 Nome2 = SA30.A3Nome,
                                 Telefone = SA10.A1Tel,
                                 Celular = SA10.A1Celular,
                                 Municipio = SA10.A1Mun,
                                 Estado = SA10.A1Est
                             }
                            ).ToList();

                using ExcelPackage package = new ExcelPackage();
                package.Workbook.Worksheets.Add("Cadastros Medicos");

                var sheet = package.Workbook.Worksheets.SingleOrDefault(x => x.Name == "Cadastros Medicos");

                sheet.Cells[1, 1].Value = "Codigo";
                sheet.Cells[1, 2].Value = "Nome";
                sheet.Cells[1, 3].Value = "CodVenda";
                sheet.Cells[1, 4].Value = "Nome2";
                sheet.Cells[1, 5].Value = "Telefone";
                sheet.Cells[1, 6].Value = "Celular";
                sheet.Cells[1, 7].Value = "Municipio";
                sheet.Cells[1, 8].Value = "Estado";

                int i = 2;

                Relatorio.ForEach(Pedido =>
                {
                    sheet.Cells[i, 1].Value = Pedido.Codigo;
                    sheet.Cells[i, 2].Value = Pedido.Nome;
                    sheet.Cells[i, 3].Value = Pedido.CodVenda;
                    sheet.Cells[i, 4].Value = Pedido.Nome2;
                    sheet.Cells[i, 5].Value = Pedido.Telefone;
                    sheet.Cells[i, 6].Value = Pedido.Celular;
                    sheet.Cells[i, 7].Value = Pedido.Municipio;
                    sheet.Cells[i, 8].Value = Pedido.Estado;

                    i++;
                });

                //var format = sheet.Cells[i, 3, i, 4];
                //format.Style.Numberformat.Format = "";

                sheet.Cells[sheet.Dimension.Address].AutoFitColumns();
                using MemoryStream stream = new MemoryStream();
                package.SaveAs(stream);
                return File(stream.ToArray(), "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", "CadastroMedicosInter.xlsx");
            }
            catch (Exception e)
            {
                string user = User.Identity.Name.Split("@")[0].ToUpper();
                Logger.Log(e, SGID, "CadastroMedicosInter Excel", user);

                return LocalRedirect("/error");
            }
        }
    }
}

SGID/Pages/Relatorios/Gerencial/CirurgiasNFaturadas.cshtml
@page
@model SGID.Pages.Relatorios.Gerencial.CirurgiasNFaturadasModel
@{
    ViewData["Title"] = "Relatorio Cirurgias Não Faturadas Denuo";
    if (User.IsInRole("Diretoria") && !User.IsInRole("Admin"))
    {
        Layout = "_LayoutDiretoria";
    }
    else
    {
        Layout = "_LayoutNovo";
    }
}

@using (@Html.BeginForm(FormMethod.Post))
{
    <div class="row">
        <div class="form-group mx-sm-3 mb-2 col-lg-1">
            <button type="submit" class="btn btn-secondary mb-2" asp-page-handler="Export"><i class="fa-solid fa-file-excel"></i> Exportar Excel</button>
        </div>
    </div>
}

<div class="panel">
    <div class="panel-body">
        <table id="demo-dt-addrow" class="table table-striped table-bordered" cellspacing="0" width="100%">
            <thead>
                <tr>
                    <th class="text-center">
                        Tipo de Operação
                    </th>
                    <th class="text-center">
                        Periodo
                    </th>
                    <th class="text-center">
                        Total
                    </th>
                </tr>
            </thead>
            <tbody>
                @foreach(var data in Model.RelatorioContagem)
                {
                <tr>
                    <td>@Html.DisplayFor(model=> data.TipoOper)</td>
                    <td>@Html.DisplayFor(model=> data.Periodo)</td>
                    <td>@Html.DisplayFor(model=> data.Valor)</td>
                </tr>
                }
            </tbody>
        </table>
    </div>
</div>

<div class="panel">
    <div class="panel-body">
        <table id="demo-dt-addrow" class="table table-striped table-bordered" cellspacing="0" width="100%">
            <thead>
                <tr>
                    <th class="text-center">
                        Operação  
                    </th>
                    <th class="text-center">
                        Cli Fat.
                    </th>
                    <th class="text-center">
                        Vendedor 
                    </th>
                     <th class="text-center">
                        DT.Cirurgia
                    </th>
                    <th class="text-center">
                        Emissão
                    </th>
                    <th class="text-center">
                        Num. Pedido
                    </th>
                    <th class="text-center">
                        Cliente Entrega
                    </th>
                    <th class="text-center">
                        Valor
                    </th>
                </tr>
            </thead>
            <tbody>
                @foreach(var data in Model.RelatorioCirurgias)
                {
                <tr>
                    <td>@Html.DisplayFor(model=> data.TipoOper)</td>
                    <td>@Html.DisplayFor(model=> data.CliFat)</td>
                    <td>@Html.DisplayFor(model=> data.NomeVend)</td>
                    <td>@Html.DisplayFor(model=> $"{data.DataCirurgia.Substring(6,2)}/{data.DataCirurgia.Substring(4,2)}/{data.DataCirurgia.Substring(0,4)}" )</td>
                    <td>@Html.DisplayFor(model=> $"{data.Emissao.Substring(6,2)}/{data.Emissao.Substring(4,2)}/{data.Emissao.Substring(0,4)}" )</td>
                    <td>@Html.DisplayFor(model=> data.Numero)</td>
                    <td>@Html.DisplayFor(model=> data.CliEnt)</td>
                    <td>@string.Format("{0:N2}", data.ValTot)</td>
                </tr>
                }
            </tbody>
        </table>
    </div>
</div>


<div class="panel">
    <div class="panel-body">
        <table id="demo-dt-addrow" class="table table-striped table-bordered" cellspacing="0" width="100%">
            <thead>
                <tr>
                    <th class="text-center">
                        Tipo de Operação
                    </th>
                    <th class="text-center">
                        Periodo
                    </th>
                    <th class="text-center">
                        Total
                    </th>
                </tr>
            </thead>
            <tbody>
                @foreach(var data in Model.RelatorioValor)
                {
                <tr>
                    <td>@Html.DisplayFor(model=> data.TipoOper)</td>
                    <td>@Html.DisplayFor(model=> data.Periodo)</td>
                    <td>@string.Format("{0:N2}", data.Valor)</td>
                </tr>
                }
            </tbody>
        </table>
    </div>
</div>

SGID/Pages/Relatorios/Gerencial/CirurgiasNFaturadasInter.cshtml
@page
@model SGID.Pages.Relatorios.Gerencial.CirurgiasNFaturadasInterModel
@{
    ViewData["Title"] = "Relatorio Cirurgias Não Faturadas Inter";
    if (User.IsInRole("Diretoria") && !User.IsInRole("Admin"))
    {
        Layout = "_LayoutDiretoria";
    }
    else
    {
        Layout = "_LayoutNovo";
    }
}

@using (@Html.BeginForm(FormMethod.Post))
{
    <div class="row">
        <div class="form-group mx-sm-3 mb-2 col-lg-1">
            <button type="submit" class="btn btn-secondary mb-2" asp-page-handler="Export"><i class="fa-solid fa-file-excel"></i> Exportar Excel</button>
        </div>
    </div>
}

<div class="panel">
    <div class="panel-body">
        <table id="demo-dt-addrow" class="table table-striped table-bordered" cellspacing="0" width="100%">
            <thead>
                <tr>
                    <th class="text-center">
                        Tipo de Operação
                    </th>
                    <th class="text-center">
                        Periodo
                    </th>
                    <th class="text-center">
                        Total
                    </th>
                </tr>
            </thead>
            <tbody>
                @foreach(var data in Model.RelatorioContagem)
                {
                <tr>
                    <td>@Html.DisplayFor(model=> data.TipoOper)</td>
                    <td>@Html.DisplayFor(model=> data.Periodo)</td>
                    <td>@Html.DisplayFor(model=> data.Valor)</td>
                </tr>
                }
            </tbody>
        </table>
    </div>
</div>

<div class="panel">
    <div class="panel-body">
        <table id="demo-dt-addrow" class="table table-striped table-bordered" cellspacing="0" width="100%">
            <thead>
                <tr>
                    <th class="text-center">
                        Operação  
                    </th>
                    <th class="text-center">
                        Cli Fat.
                    </th>
                    <th class="text-center">
                        Vendedor 
                    </th>
                     <th class="text-center">
                        DT.Cirurgia
                    </th>
                    <th class="text-center">
                        Emissão
                    </th>
                    <th class="text-center">
                        Num. Pedido
                    </th>
                    <th class="text-center">
                        Cliente Entrega
                    </th>
                    <th class="text-center">
                        Valor
                    </th>
                </tr>
            </thead>
            <tbody>
                @foreach(var data in Model.RelatorioCirurgias)
                {
                <tr>
                    <td>@Html.DisplayFor(model=> data.TipoOper)</td>
                    <td>@Html.DisplayFor(model=> data.CliFat)</td>
                    <td>@Html.DisplayFor(model=> data.NomeVend)</td>
                    <td>@Html.DisplayFor(model=> $"{data.DataCirurgia.Substring(6,2)}/{data.DataCirurgia.Substring(4,2)}/{data.DataCirurgia.Substring(0,4)}" )</td>
                    <td>@Html.DisplayFor(model=> $"{data.Emissao.Substring(6,2)}/{data.Emissao.Substring(4,2)}/{data.Emissao.Substring(0,4)}" )</td>
                    <td>@Html.DisplayFor(model=> data.Numero)</td>
                    <td>@Html.DisplayFor(model=> data.CliEnt)</td>
                    <td>@string.Format("{0:N2}", data.ValTot)</td>
                </tr>
                }
            </tbody>
        </table>
    </div>
</div>


<div class="panel">
    <div class="panel-body">
        <table id="demo-dt-addrow" class="table table-striped table-bordered" cellspacing="0" width="100%">
            <thead>
                <tr>
                    <th class="text-center">
                        Tipo de Operação
                    </th>
                    <th class="text-center">
                        Periodo
                    </th>
                    <th class="text-center">
                        Total
                    </th>
                </tr>
            </thead>
            <tbody>
                @foreach(var data in Model.RelatorioValor)
                {
                <tr>
                    <td>@Html.DisplayFor(model=> data.TipoOper)</td>
                    <td>@Html.DisplayFor(model=> data.Periodo)</td>
                    <td>@string.Format("{0:N2}", data.Valor)</td>
                </tr>
                }
            </tbody>
        </table>
    </div>
</div>